// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj9Aw46b46jkxiFgwaW6HCjClM2nExr5s',
    appId: '1:830118321018:web:27fb51716a6ce6eb2994c3',
    messagingSenderId: '830118321018',
    projectId: 'socialmedia-group',
    authDomain: 'socialmedia-group.firebaseapp.com',
    storageBucket: 'socialmedia-group.appspot.com',
    measurementId: 'G-DF8LPBMJZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoFgNclw5YfZtYLoNnK6LsLXbyWkK7M-M',
    appId: '1:830118321018:android:8455201ab46ae6ef2994c3',
    messagingSenderId: '830118321018',
    projectId: 'socialmedia-group',
    storageBucket: 'socialmedia-group.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5uWEKd3lvLGedoSYDmZVEYz4DpHcvcsk',
    appId: '1:830118321018:ios:4e3c4a6e4938e2952994c3',
    messagingSenderId: '830118321018',
    projectId: 'socialmedia-group',
    storageBucket: 'socialmedia-group.appspot.com',
    androidClientId: '830118321018-4coelg3aoe9ps02e1ph5rvnt3hgga67r.apps.googleusercontent.com',
    iosClientId: '830118321018-hi8mdjna9irp4iqee2tdeg75qd3lhiv3.apps.googleusercontent.com',
    iosBundleId: 'com.socialmediaapp.app',
  );
}
